runtime: nodejs

env: flex

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "strapi"
  DATABASE_USERNAME: "server"
  DATABASE_PASSWORD: "rJl6yGvnMJpggBws"
  INSTANCE_CONNECTION_NAME: "modern-binder-317614:europe-north1:aniseria-strapi"

beta_settings:
  cloud_sql_instances: "modern-binder-317614:europe-north1:aniseria-strapi"
