runtime: nodejs14

instance_class: F2

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "postgres"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "rJl6yGvnMJpggBws"
  INSTANCE_CONNECTION_NAME: "modern-binder-317614:europe-west1:server"
beta_settings:
  cloud_sql_instances: "modern-binder-317614:europe-west1:server"
